// Generated by scripts/generate-image-manifest.mjs — do not edit by hand.
// Run `npm run lqip` to regenerate after adding or replacing images.

export type ImageManifestEntry = {
  dominantColor: string
  thumbHash: string
  width: number
  height: number
  hasAlpha: boolean
}

export const imageManifest: Record<string, ImageManifestEntry> = {
  "/android-chrome-192.png": {
    "dominantColor": "rgb(248, 248, 232)",
    "thumbHash": "uOcFHwT4N7iGeId+g6pnaIiFiG/o+IYO",
    "width": 192,
    "height": 192,
    "hasAlpha": false
  },
  "/android-chrome-512.png": {
    "dominantColor": "rgb(248, 248, 232)",
    "thumbHash": "uOcFHwT4N7iGeId+g6pnaIiFiG/o+IYO",
    "width": 512,
    "height": 512,
    "hasAlpha": false
  },
  "/icon-16.png": {
    "dominantColor": "rgb(248, 248, 232)",
    "thumbHash": "uOcFHwT4N6iGeId+g6pnaJiFiG/o+IYO",
    "width": 16,
    "height": 16,
    "hasAlpha": false
  },
  "/icon-32.png": {
    "dominantColor": "rgb(248, 248, 232)",
    "thumbHash": "uOcFHwT4N7iGeId+g6pnaJiFiG/o+IYO",
    "width": 32,
    "height": 32,
    "hasAlpha": false
  },
  "/images/biconomy/api/1.webp": {
    "dominantColor": "rgb(200, 200, 200)",
    "thumbHash": "8gcGBYBwh4eUiIh1d5eIhyC38I30",
    "width": 2008,
    "height": 1506,
    "hasAlpha": false
  },
  "/images/biconomy/api/2.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "9AcKBYA/PC2Xhod1eIeIdxVsrz4J",
    "width": 2006,
    "height": 1504,
    "hasAlpha": false
  },
  "/images/biconomy/api/3.webp": {
    "dominantColor": "rgb(232, 232, 232)",
    "thumbHash": "9gcGBYCfmGl2iHiGh4d3dwCZ+W9m",
    "width": 2006,
    "height": 1506,
    "hasAlpha": false
  },
  "/images/biconomy/api/biconomyx-pp.webp": {
    "dominantColor": "rgb(232, 232, 232)",
    "thumbHash": "NggGBwD7OYaIeId9c6pneIiHVoBHB3oG",
    "width": 400,
    "height": 400,
    "hasAlpha": false
  },
  "/images/biconomy/api/flows/flow-1-1.webp": {
    "dominantColor": "rgb(200, 200, 200)",
    "thumbHash": "8gcGBYBwh4eUiIh1d5eIhxKm0J71",
    "width": 1200,
    "height": 900,
    "hasAlpha": false
  },
  "/images/biconomy/api/flows/flow-1-2.webp": {
    "dominantColor": "rgb(232, 232, 232)",
    "thumbHash": "9gcGBYCfmGl2iHiGh4d3dwGZ6m9W",
    "width": 1200,
    "height": 900,
    "hasAlpha": false
  },
  "/images/biconomy/api/flows/flow-1-3.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "8QcOBYAfLlt2h3h2iIh4d2StvykF",
    "width": 1200,
    "height": 900,
    "hasAlpha": false
  },
  "/images/biconomy/api/flows/flow-2-1.webp": {
    "dominantColor": "rgb(200, 200, 200)",
    "thumbHash": "8gcGBYBQmKapiYdyeKdoh0DM8Tvj",
    "width": 1200,
    "height": 900,
    "hasAlpha": false
  },
  "/images/biconomy/api/flows/flow-2-2.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "9gcKBYCPiHeJeHh1iJh4hzCa+Vxm",
    "width": 1200,
    "height": 900,
    "hasAlpha": false
  },
  "/images/biconomy/api/flows/flow-2-3.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "9QcKBYA/PC2Xhod1eIeIdzRtvywJ",
    "width": 1200,
    "height": 900,
    "hasAlpha": false
  },
  "/images/biconomy/api/flows/flow-3-1.webp": {
    "dominantColor": "rgb(200, 200, 200)",
    "thumbHash": "8gcGBQDWZZCKaIeHiHeHiNiAdPK3",
    "width": 1200,
    "height": 1600,
    "hasAlpha": false
  },
  "/images/biconomy/api/flows/flow-4-1.webp": {
    "dominantColor": "rgb(200, 200, 200)",
    "thumbHash": "7gcKBQAPHnd4qIeHeHiHh/dzjMA4",
    "width": 1200,
    "height": 1600,
    "hasAlpha": false
  },
  "/images/biconomy/api/send_assets.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "8wcGBIAnWDeKd2mAhpcZLG8+DQ==",
    "width": 478,
    "height": 254,
    "hasAlpha": false
  },
  "/images/biconomy/demos/after.webp": {
    "dominantColor": "rgb(168, 136, 104)",
    "thumbHash": "XkkGDwKHh3dwiIiGh2eHeIeH1wt3v5AC",
    "width": 1040,
    "height": 1040,
    "hasAlpha": false
  },
  "/images/biconomy/demos/before.webp": {
    "dominantColor": "rgb(152, 120, 88)",
    "thumbHash": "nkkGDwB4d3dgiHeId3iId3h3hwi4dIAF",
    "width": 1040,
    "height": 1040,
    "hasAlpha": false
  },
  "/images/biconomy/demos/game.webp": {
    "dominantColor": "rgb(120, 120, 136)",
    "thumbHash": "XAcKFYKot1ZpZYSAbUaIi4x9kPc2",
    "width": 3444,
    "height": 2450,
    "hasAlpha": false
  },
  "/images/biconomy/demos/web.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "h/cBBIC8eHaOineGZnCon2uX+Q==",
    "width": 3444,
    "height": 2153,
    "hasAlpha": false
  },
  "/images/biconomy/demos/web3_abstractor.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "nSgOFIQmW3g0poewios3RHBDBA==",
    "width": 546,
    "height": 302,
    "hasAlpha": false
  },
  "/images/biconomy/flows/gas_tank_setup_after.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "hgcCBIBJ1iiHeneCj4hoj53yqA==",
    "width": 2982,
    "height": 1693,
    "hasAlpha": false
  },
  "/images/biconomy/flows/gas_tank_setup_after_2.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "hwcCBIAplZmIiHhwnoYaf+fZ9w==",
    "width": 2982,
    "height": 1695,
    "hasAlpha": false
  },
  "/images/biconomy/flows/gas_tank_setup_before.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "xwcCDICMU2evWXZ6mlb/i7mvpw==",
    "width": 2979,
    "height": 1692,
    "hasAlpha": false
  },
  "/images/biconomy/flows/network_change_prompt_after.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "hwcCBIB/IXWcaIdVyni/iPZtdw==",
    "width": 2981,
    "height": 1695,
    "hasAlpha": false
  },
  "/images/biconomy/flows/network_change_prompt_before.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "xwcCDICOQ3evWIZ4q2ffieePiQ==",
    "width": 2979,
    "height": 1692,
    "hasAlpha": false
  },
  "/images/biconomy/flows/paymaster_card_after.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "hwcCBICEXJdfuHZ7mZb9bPqOqg==",
    "width": 2981,
    "height": 1695,
    "hasAlpha": false
  },
  "/images/biconomy/flows/paymaster_card_before.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "xwcCDICleodvmneNmoj+evmeqQ==",
    "width": 2979,
    "height": 1692,
    "hasAlpha": false
  },
  "/images/biconomy/flows/paymaster_empty_state_after.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "xwcCBIAqZqSGe3aIh2Bqn8/4ug==",
    "width": 2982,
    "height": 1696,
    "hasAlpha": false
  },
  "/images/biconomy/flows/paymaster_empty_state_before.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "xwcCDIBeUUafaIhUzWbvevi/lg==",
    "width": 2982,
    "height": 1696,
    "hasAlpha": false
  },
  "/images/biconomy/flows/paymaster_overview_after.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "hwcCDIC/mFe7i3hiilSJj4746A==",
    "width": 2982,
    "height": 1695,
    "hasAlpha": false
  },
  "/images/biconomy/flows/paymaster_overview_before.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "yPcBDIJ4RXaPaXahnYX+e7mc9w==",
    "width": 2979,
    "height": 1691,
    "hasAlpha": false
  },
  "/images/biconomy/flows/register_paymaster_dialog_after.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "hwcCBIAdkTieeHhSz2h/e/WaZg==",
    "width": 2982,
    "height": 1696,
    "hasAlpha": false
  },
  "/images/biconomy/flows/register_paymaster_dialog_before.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "h/cBBIAbhYePdYllm3TPerZflw==",
    "width": 2979,
    "height": 1695,
    "hasAlpha": false
  },
  "/images/biconomy/multiverse_pill.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "exiCCoQeeIl5eX93hnBnCAgYiIdxgkc=",
    "width": 546,
    "height": 236,
    "hasAlpha": true
  },
  "/images/biconomy/multiverse_poster.webp": {
    "dominantColor": "rgb(40, 24, 8)",
    "thumbHash": "DimKDAQPCFiYN4d3lhCZmHS/tPR4B3iPAA==",
    "width": 1684,
    "height": 2382,
    "hasAlpha": true
  },
  "/images/biconomy/sa/breakfast.webp": {
    "dominantColor": "rgb(200, 216, 232)",
    "thumbHash": "XvcRHQJJdq+Gd3mIh3mIeFCqKDgJ",
    "width": 1200,
    "height": 1600,
    "hasAlpha": false
  },
  "/images/biconomy/sa/building-a-bridge.webp": {
    "dominantColor": "rgb(72, 88, 72)",
    "thumbHash": "HPgNDAJn+XeoiJhnZ3cYim/2KA==",
    "width": 900,
    "height": 1600,
    "hasAlpha": false
  },
  "/images/biconomy/sa/design-team-bico.webp": {
    "dominantColor": "rgb(232, 248, 248)",
    "thumbHash": "JugVHAJ393inh3dXeIiHgHgR+A==",
    "width": 900,
    "height": 1600,
    "hasAlpha": false
  },
  "/images/biconomy/sa/feast-in-bali.webp": {
    "dominantColor": "rgb(120, 88, 56)",
    "thumbHash": "mhgKHQKml113B3iYeZiHhll/6/f5",
    "width": 1067,
    "height": 1600,
    "hasAlpha": false
  },
  "/images/biconomy/sa/flor-and-me.webp": {
    "dominantColor": "rgb(24, 24, 24)",
    "thumbHash": "UwgKJQKHin93R4kndoZ3eIdlgEQG",
    "width": 1066,
    "height": 1600,
    "hasAlpha": false
  },
  "/images/biconomy/sa/flor-azaan-football.webp": {
    "dominantColor": "rgb(8, 8, 8)",
    "thumbHash": "DfkJLQJYZZB3eId5hnd4eIeAl/ZH",
    "width": 1200,
    "height": 1600,
    "hasAlpha": false
  },
  "/images/biconomy/sa/gang.webp": {
    "dominantColor": "rgb(8, 104, 136)",
    "thumbHash": "3gQJFQaYiH+Id2lId3Z4Z2OgQgcZ",
    "width": 1066,
    "height": 1600,
    "hasAlpha": false
  },
  "/images/biconomy/sa/georgios-and-me.webp": {
    "dominantColor": "rgb(8, 8, 8)",
    "thumbHash": "lRgSFQKZmI+Hl3dnd4iHiLJvCft0",
    "width": 1200,
    "height": 1600,
    "hasAlpha": false
  },
  "/images/biconomy/sa/kalyug-ka-bazaar.webp": {
    "dominantColor": "rgb(248, 216, 200)",
    "thumbHash": "nlkOFQIKeIN6a4i3eIiIRwl3gmhQ",
    "width": 1200,
    "height": 1600,
    "hasAlpha": false
  },
  "/images/biconomy/sa/notes.webp": {
    "dominantColor": "rgb(8, 8, 8)",
    "thumbHash": "MheCC4A4qsdvZA/ldH8IWGdnN4iAink=",
    "width": 460,
    "height": 248,
    "hasAlpha": true
  },
  "/images/biconomy/sa/scooters-in-baku.webp": {
    "dominantColor": "rgb(152, 200, 248)",
    "thumbHash": "IecNLYhViIiPiHePd1eJdIlxgBgH",
    "width": 1600,
    "height": 1200,
    "hasAlpha": false
  },
  "/images/paper-roll.webp": {
    "dominantColor": "rgb(8, 8, 8)",
    "thumbHash": "cheCC4A4qsdvZA/kdH8IWGdnN4iAink=",
    "width": 207,
    "height": 112,
    "hasAlpha": true
  },
  "/images/rr/north-star-bg.webp": {
    "dominantColor": "rgb(232, 232, 216)",
    "thumbHash": "tgiCAoAeU5RApnWrv6b5mmdnlnhwaAo=",
    "width": 299,
    "height": 135,
    "hasAlpha": true
  },
  "/images/rr/rr-card-texture.webp": {
    "dominantColor": "rgb(232, 216, 200)",
    "thumbHash": "tgiCBQAHV8aYp2V1CLJVD3i4T1X3qWRXOQ==",
    "width": 1024,
    "height": 1024,
    "hasAlpha": true
  },
  "/images/rr/rr-card-v1.webp": {
    "dominantColor": "rgb(200, 232, 216)",
    "thumbHash": "8ceFDAAe9vdnuGeCXr+XJYBLQJCGJ4h5Ag==",
    "width": 449,
    "height": 617,
    "hasAlpha": true
  },
  "/images/rr/rr-card-v2.webp": {
    "dominantColor": "rgb(184, 216, 216)",
    "thumbHash": "sseBBAAepPZ4V3iLJj/o9odeULCIOIh7Aw==",
    "width": 457,
    "height": 626,
    "hasAlpha": true
  },
  "/images/rr/rr-card-v3.webp": {
    "dominantColor": "rgb(184, 216, 216)",
    "thumbHash": "sreBBAAe9XanqDeKVT+29qxaULB4OIh7Aw==",
    "width": 452,
    "height": 625,
    "hasAlpha": true
  },
  "/images/rr/rr-card-v4.webp": {
    "dominantColor": "rgb(232, 216, 152)",
    "thumbHash": "pzmKDAIeNrdnB4d6UdUG94deUMCIOIh7Aw==",
    "width": 458,
    "height": 632,
    "hasAlpha": true
  },
  "/images/rr/rr-card-v5-art.webp": {
    "dominantColor": "rgb(8, 8, 8)",
    "thumbHash": "muWFDYA2j1E7p6eFZqDVDVvtC2OBeFdaaA==",
    "width": 147,
    "height": 133,
    "hasAlpha": true
  },
  "/images/rr/rr-card-v5.webp": {
    "dominantColor": "rgb(24, 24, 72)",
    "thumbHash": "lTeGKwoemoH4hoeXcH0HuAUFfHeDtzc=",
    "width": 427,
    "height": 632,
    "hasAlpha": true
  },
  "/images/rr/rr-hand-deck-fan.webp": {
    "dominantColor": "rgb(8, 8, 8)",
    "thumbHash": "4BiGDYI2rKadVk8gJjVwWgSHCYeIeHJ5dw==",
    "width": 907,
    "height": 886,
    "hasAlpha": true
  },
  "/images/rr/rr-interface-desktop.webp": {
    "dominantColor": "rgb(120, 120, 136)",
    "thumbHash": "XAeKFIIPqLh4dJBNyMgHeW/y8HB4eHiHBw==",
    "width": 1896,
    "height": 1348,
    "hasAlpha": true
  },
  "/images/rr/rr-resolving-icon.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "JbmCDQIkmUWOgmQJxzabsAV4BolnmXGLeQ==",
    "width": 1024,
    "height": 1024,
    "hasAlpha": true
  },
  "/images/rr/rr-s2-figma-ref.webp": {
    "dominantColor": "rgb(24, 40, 24)",
    "thumbHash": "StiBBQABqLS0OVQEuPJVqPNc9lpkRHp2tw==",
    "width": 1024,
    "height": 1024,
    "hasAlpha": true
  },
  "/images/rr/rr-score.webp": {
    "dominantColor": "rgb(8, 8, 8)",
    "thumbHash": "abqCAYAR2VJ5hlBFhl9l+Ci3iHiAaug=",
    "width": 228,
    "height": 29,
    "hasAlpha": true
  },
  "/images/rr/rr-sketch-1.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "OigCCwT0ePhJd5m5aHKAMwc=",
    "width": 1328,
    "height": 2704,
    "hasAlpha": false
  },
  "/images/rr/rr-sketch-2.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "/AeCBAAOb4RnKKi0+MyW4NBfUGCIKIiGAg==",
    "width": 820,
    "height": 1176,
    "hasAlpha": true
  },
  "/images/rr/rr-sketch-3.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "+weCBAAOhwzE2CjfrU34mM+voJB4KIeJAg==",
    "width": 820,
    "height": 1170,
    "hasAlpha": true
  },
  "/images/rr/rr-sketch-4.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "/AeCAwAOm1xcUN7/zNifjQoKiYdymCg=",
    "width": 804,
    "height": 1176,
    "hasAlpha": true
  },
  "/images/rr/rr-sketch-5.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "/gcCBYA/2LJRl5eEdYZnlD9D9Oa5",
    "width": 2272,
    "height": 1744,
    "hasAlpha": false
  },
  "/images/rr/rr-sketch-6.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "/gcCBoCcxFqQaZtZmLh1iXiXm5CI9ag=",
    "width": 1768,
    "height": 1500,
    "hasAlpha": false
  },
  "/images/rr/rr-story-bg-texture.webp": {
    "dominantColor": "rgb(232, 216, 200)",
    "thumbHash": "tgiCBQAHV8aYp2V1CLJVD3i4T1X3qWRXOQ==",
    "width": 1024,
    "height": 1024,
    "hasAlpha": true
  },
  "/images/rr/rug-bg.webp": {
    "dominantColor": "rgb(24, 88, 24)",
    "thumbHash": "zKgBBIKRtZXAdbVsdmZuPwID3g==",
    "width": 1440,
    "height": 900,
    "hasAlpha": false
  },
  "/images/rr/story-terra-bg.webp": {
    "dominantColor": "rgb(232, 216, 200)",
    "thumbHash": "txgCBABQixOzZy/Up2TPt/Vleg==",
    "width": 368,
    "height": 624,
    "hasAlpha": false
  },
  "/images/rr/story-yellow-bg.webp": {
    "dominantColor": "rgb(232, 216, 200)",
    "thumbHash": "tggCBABQixOzZy/Up3TPufVUeg==",
    "width": 368,
    "height": 624,
    "hasAlpha": false
  },
  "/marks/beringer/01.webp": {
    "dominantColor": "rgb(184, 24, 24)",
    "thumbHash": "KIkOFwqLhEtgh3dxhziIeIeHWvbodZ8O",
    "width": 1080,
    "height": 1080,
    "hasAlpha": false
  },
  "/marks/beringer/02.webp": {
    "dominantColor": "rgb(232, 200, 184)",
    "thumbHash": "KnkKDwg8eqaflodxeNd4OHiKNxv2wmAP",
    "width": 1080,
    "height": 1080,
    "hasAlpha": false
  },
  "/marks/beringer/03.webp": {
    "dominantColor": "rgb(184, 24, 24)",
    "thumbHash": "XskOHwwGaJh4iIiEeYh4N6iHd3/I94cM",
    "width": 1080,
    "height": 1080,
    "hasAlpha": false
  },
  "/marks/beringer/04.webp": {
    "dominantColor": "rgb(184, 24, 24)",
    "thumbHash": "YqkOFwxAp3mjiHeUiGeIeIh4+Nu2v10L",
    "width": 1080,
    "height": 1080,
    "hasAlpha": false
  },
  "/marks/codezeros/01.webp": {
    "dominantColor": "rgb(216, 216, 216)",
    "thumbHash": "KwgKBYBwd3eId4h2iHeId793+Xl5",
    "width": 3000,
    "height": 2109,
    "hasAlpha": false
  },
  "/marks/codezeros/02.webp": {
    "dominantColor": "rgb(56, 72, 72)",
    "thumbHash": "2fcNDYD5mnnnmXpXeEdZd7TQch+d",
    "width": 3000,
    "height": 2250,
    "hasAlpha": false
  },
  "/marks/ecochain/01.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "PQgGBICWyamId3efZnYJh4JwCA==",
    "width": 3000,
    "height": 1688,
    "hasAlpha": false
  },
  "/marks/ecochain/02.webp": {
    "dominantColor": "rgb(216, 216, 216)",
    "thumbHash": "b/kJJYiPfJqUeHiZZxeIdaJ/K8z3",
    "width": 3000,
    "height": 2200,
    "hasAlpha": false
  },
  "/marks/furrmark/01.webp": {
    "dominantColor": "rgb(200, 200, 200)",
    "thumbHash": "7gcGDYIgm3dDqXmqidiLiZ+u9dhL",
    "width": 3000,
    "height": 2008,
    "hasAlpha": false
  },
  "/marks/furrmark/02.webp": {
    "dominantColor": "rgb(216, 216, 216)",
    "thumbHash": "NfgFBYBlaHmKd3eAemmIfU+Cc6wJ",
    "width": 3000,
    "height": 2250,
    "hasAlpha": false
  },
  "/marks/furrmark/03.webp": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "OPgFBYBnenmKh3dgaZh4c2+FPncI",
    "width": 3000,
    "height": 2250,
    "hasAlpha": false
  },
  "/marks/kilti/01.webp": {
    "dominantColor": "rgb(216, 216, 216)",
    "thumbHash": "XwgKDQKreEq1+lvWlmepiVt0/8ZD",
    "width": 960,
    "height": 1280,
    "hasAlpha": false
  },
  "/marks/slangbusters/01.webp": {
    "dominantColor": "rgb(120, 72, 8)",
    "thumbHash": "3DcKZIQf00aDjZeLZniQdxjvag==",
    "width": 3000,
    "height": 1688,
    "hasAlpha": false
  },
  "/noise-bg.png": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "PfgBBwCadmaIh1iYmrtJRkmvWglG/2YK",
    "width": 400,
    "height": 400,
    "hasAlpha": false
  },
  "/og-image.png": {
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "/PcBDICHl5h/dnaEiHiYf4P4Nw==",
    "width": 1200,
    "height": 630,
    "hasAlpha": false
  }
}
