import { readFileSync } from 'node:fs'

// The shipped version, surfaced as a response header. `npm run smoke` polls it
// to tell whether the deploy it is about to test is actually the new one — a
// check that runs against the previous deploy passes green and tells you
// nothing, which is worse than no check at all.
const APP_VERSION = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8')).version

// ── Security headers — SOURCE OF TRUTH ─────────────────────────────────────
// Declared here, not only in netlify.toml, because Netlify's [[headers]] cover
// files it serves straight from the CDN (everything in public/) and NOT
// responses generated by the Next runtime — which is every actual page. For
// months that meant the whole security posture applied to the images and the
// resume PDF while /, /all, /rr and the rest went entirely uncovered.
//
// So the two files split the job by what serves the response:
//   • THIS list  → every page and route handler Next renders.
//   • netlify.toml → static files under public/ (the resume PDF included).
// They must stay identical. netlify.toml points back here; `npm run smoke`
// checks the live site for both halves after a deploy.
//
// X-Frame-Options is SAMEORIGIN, never DENY: DENY forbids framing even by our
// own pages, and /resume lays the PDF in a same-origin frame. Under DENY the
// browser refuses it and the route reads as a blank page — invisible locally,
// since `next dev` serves none of these headers.
const CSP_REPORT_ONLY = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline' https://api.emailjs.com https://cloud.umami.is",
  "style-src 'self' 'unsafe-inline'",
  "font-src 'self'",
  "img-src 'self' data: blob:",
  "connect-src 'self' https://api.emailjs.com https://gateway.umami.is",
  // frame-src covers what WE embed: the /resume PDF (self), the book-a-call
  // calendar, the /biconomy Notion + Figma evidence embeds. An embed missing
  // here goes blank the moment this policy is ever enforced.
  "frame-src 'self' https://calendar.app.google https://niharbhagat.notion.site https://embed.figma.com",
  // frame-ancestors covers who may embed US. Not covered by default-src.
  "frame-ancestors 'self'",
  "form-action 'self'",
  "base-uri 'self'",
  'report-uri /csp-report',
].join('; ')

const SECURITY_HEADERS = [
  { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
  { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()' },
  { key: 'Content-Security-Policy-Report-Only', value: CSP_REPORT_ONLY },
]

/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    formats: ['image/avif', 'image/webp'],
    // Allowed quality values for the next/image optimizer. Next 15 silently
    // clamps any `quality` prop not listed here back into the allowed set,
    // so the values <Img> reaches for (90 for lossy source, 100 for
    // lossless / near-lossless source) must be explicitly enumerated. 75
    // stays in for consumers that opt down (thumbnails, etc.).
    qualities: [75, 90, 100],
  },
  experimental: {
    optimizePackageImports: ['framer-motion'],
  },
  // The works hub moved from /selected to /all (the "Work Essay" redesign;
  // "bench" remains the internal codename). Old inbound links + the prior
  // og:canonical keep resolving via a permanent redirect.
  async redirects() {
    return [
      { source: '/selected', destination: '/all', permanent: true },
    ]
  },
  async headers() {
    return [{
      source: '/:path*',
      headers: [...SECURITY_HEADERS, { key: 'X-App-Version', value: APP_VERSION }],
    }]
  },
  // Pretty, shareable aliases for the hub's two browse modes. Each rewrites to
  // the single /all surface; the active tab is resolved CLIENT-side from the
  // browser URL (the rewrite hides its destination query from the client, but
  // the pathname stays visible — see /all's "Deep-link entry & tab order"
  // anomaly). No server searchParams read: that would make /all dynamic. The
  // address bar keeps the pretty alias (rewrites don't change the URL).
  async rewrites() {
    return [
      { source: '/cases',    destination: '/all?cases' },
      { source: '/showcase', destination: '/all?showcase' },
      // Blast Radius is a standalone prototype in public/, not a route. In
      // production Netlify serves it off the CDN via the matching [[redirects]]
      // in netlify.toml — that rule wins and this one never fires. It exists so
      // `next dev` resolves the same URL locally instead of 404ing.
      { source: '/blast-radius', destination: '/blast-radius/index.html' },
    ]
  },
}
export default nextConfig
