// Generated by scripts/generate-lqip-samples.mjs — do not edit by hand.
export const lqipSamples = [
  {
    "label": "UI mockup",
    "src": "/images/rr/rr-card-v5.webp",
    "dominantColor": "rgb(24, 24, 72)",
    "thumbHash": "lTeGKwoemoH4hoeXcH0HuAYGe3eDtzc=",
    "width": 214,
    "height": 316
  },
  {
    "label": "Sketch",
    "src": "/images/rr/rr-sketch-1.webp",
    "dominantColor": "rgb(248, 248, 248)",
    "thumbHash": "OigCCwT0ePhJd5m5aHKAMwc=",
    "width": 1328,
    "height": 2704
  },
  {
    "label": "Photo",
    "src": "/images/biconomy/sa/design-team-bico.webp",
    "dominantColor": "rgb(232, 248, 248)",
    "thumbHash": "JvgVHAJ393inh3dXeIiHgHgR+A==",
    "width": 900,
    "height": 1600
  },
  {
    "label": "Poster",
    "src": "/images/biconomy/multiverse_poster.webp",
    "dominantColor": "rgb(40, 24, 8)",
    "thumbHash": "ziiKDAQPCFiYN4d3lhCJp3TPw/N4CIePAA==",
    "width": 1684,
    "height": 2382
  }
] as const
